import { readFileSync, mkdirSync, existsSync } from "node:fs";
import { homedir } from "node:os";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// State directory. New installs use ~/.zumo. Existing ~/.port23 installs keep working
// untouched: if ~/.zumo is absent but a legacy ~/.port23 exists, we stay on it so a
// rename never orphans a running daemon's config, VAPID keys, or push subscriptions.
// ZUMO_HOME (or the legacy PORT23_HOME) overrides both.
const legacyHome = join(homedir(), ".port23");
const defaultHome = join(homedir(), ".zumo");
export const P23_HOME = process.env.ZUMO_HOME || process.env.PORT23_HOME
  || (existsSync(defaultHome) ? defaultHome : existsSync(legacyHome) ? legacyHome : defaultHome);
export const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

export const PENDING_DIR = join(P23_HOME, "pending");
export const RECORDINGS_DIR = join(P23_HOME, "recordings");
export const UPLOADS_DIR = join(P23_HOME, "uploads");
export const SESSIONS_META = join(P23_HOME, "sessions.json");
export const SUBSCRIPTIONS = join(P23_HOME, "subscriptions.json");

const DEFAULTS = {
  port: 7323,
  repoRoots: [join(homedir(), "my-work")],
  activityWindowMs: 3000,
  claudeBin: "claude",
  vapid: null, // { publicKey, privateKey, subject } — generated by scripts/setup.js
};

for (const d of [P23_HOME, PENDING_DIR, RECORDINGS_DIR, UPLOADS_DIR]) {
  if (!existsSync(d)) mkdirSync(d, { recursive: true });
}

function load() {
  const path = join(P23_HOME, "config.json");
  if (!existsSync(path)) return { ...DEFAULTS };
  try {
    return { ...DEFAULTS, ...JSON.parse(readFileSync(path, "utf8")) };
  } catch (e) {
    console.error(`[config] ${path} is not valid JSON, using defaults:`, e.message);
    return { ...DEFAULTS };
  }
}

const loaded = load();
const envPort = Number(process.env.ZUMO_PORT || process.env.PORT23_PORT);
const envClaudeBin = process.env.ZUMO_CLAUDE_BIN || process.env.PORT23_CLAUDE_BIN;
export const CONFIG = {
  ...loaded,
  ...(Number.isInteger(envPort) && envPort > 0 && envPort < 65536 ? { port: envPort } : {}),
  ...(envClaudeBin ? { claudeBin: envClaudeBin } : {}),
};
